// @ts-nocheck
// GENERATED by lit-serving/gen-llb-ts.js from src/lit-service.js — do not edit by hand (edit the JS, run the generator, run tests/llb-ts.test.js).
// Drop this file into apps/web/lib/literature/ and call searchLlb() from app/api/scholar/route.ts (see lit-serving/README.md).
//
// Every user-controlled value reaches ClickHouse through {name:Type} query parameters (HTTP param_*), never through string pasting.

const DB = process.env.LLB_DB || 'openalex';
const SRC = process.env.LLB_SRC_DB || 'openalex';
const SORTS = {
  "relevance": "score DESC",
  "cited": "cited DESC",
  "year": "year DESC, cited DESC",
  "fwci": "fwci DESC",
  "jif": "jif DESC, jif_est DESC",
  "pct": "cite_pct DESC, cited DESC"
};
const IDX_FLAGS = {
  "scie": "in_scie",
  "ssci": "in_ssci",
  "ahci": "in_ahci",
  "esci": "in_esci",
  "scopus": "in_scopus",
  "kci": "in_kci",
  "doaj": "in_doaj"
};

function parseQuery(q) {
  const phrases = [], words = [];
  String(q || '').replace(/"([^"]{2,200})"/g, (_, p) => { phrases.push(p.trim().toLowerCase()); return ' '; })
    // hasToken() rejects any punctuation inside a token, so "covid-19" / "c++" / "a\" are cut into letter-digit runs (all must match);
    // the exact wording can still be demanded with a "quoted phrase"
    .split(/\s+/).flatMap(w => w.toLowerCase().match(/[\p{L}\p{N}]+/gu) || []).filter(w => w.length >= 1 && w.length <= 60).forEach(w => words.push(w));
  return { words: [...new Set(words)].slice(0, 12), phrases: phrases.slice(0, 4) };
}
const isCjk = w => /[぀-ヿ㐀-鿿가-힯]/.test(w)

async function runSearch(s, exec) {
  if (!s.staged) {
    const [results, cnt] = await Promise.all([exec(s.sql, s.params), exec(s.countSql, s.params)]);
    return { results, total: cnt[0] ? Number(cnt[0].total) : null, totalIsLowerBound: false, stage: 'exact' };
  }
  const off = Number(s.params.off), lim = Number(s.params.lim);
  const [r1, c1] = await Promise.all([exec(s.stage1, s.params), exec(s.count1, s.params)]);
  const n1 = c1[0] ? Number(c1[0].total) : 0;
  const out = { results: r1, total: n1, totalIsLowerBound: n1 >= 100001, stage: 'title' };
  if (r1.length < lim) {
    const p2 = { ...s.params, off2: Math.max(0, off - n1), lim2: lim - r1.length };
    const [r2, c2] = await Promise.all([exec(s.stage2, p2), exec(s.count2, p2)]);
    const n2 = c2[0] ? Number(c2[0].total) : 0;
    out.results = r1.concat(r2); out.total = n1 + n2; out.stage = 'title+abstract'; out.totalIsLowerBound = n1 >= 100001 || n2 >= 100001;
  } else out.totalIsLowerBound = true;       // the page is full of title matches; abstract-only matches were not even counted
  return out;
}

export function buildSearch(o = {}) {
  const { words, phrases } = parseQuery(o.q);
  const params = { words, phrases }; const where = ['1'];
  const term = (col, w) => `(${isCjk(w) ? `positionUTF8(lowerUTF8(${col}), ${w ? `{w_${words.indexOf(w)}:String}` : "''"}) > 0` : `hasToken(lowerUTF8(${col}), {w_${words.indexOf(w)}:String})`})`;
  words.forEach((w, i) => { params[`w_${i}`] = w; });
  // Text predicates come in two flavours: ANY (each word in title OR abstract) and TITLE (every word / phrase in the title).  The title
  // column is ~20x smaller than the abstract, so the TITLE flavour is what makes relevance search interactive (measured: 7 s vs 120-780 s
  // under load on 11 M rows); the abstract flavour only fills the page when there are not enough title matches (see stage 2 below).
  const textAny = [], textTitle = [];
  for (const w of words) { textAny.push(`(${term('title', w)} OR ${term('abstract', w)})`); textTitle.push(term('title', w)); }
  phrases.forEach((p, i) => { params[`p_${i}`] = p; textAny.push(`(positionUTF8(lowerUTF8(title), {p_${i}:String}) > 0 OR positionUTF8(lowerUTF8(abstract), {p_${i}:String}) > 0)`); textTitle.push(`(positionUTF8(lowerUTF8(title), {p_${i}:String}) > 0)`); });
  where.push(...textAny);
  const num = (v, d) => (Number.isFinite(Number(v)) ? Number(v) : d);
  if (o.yearFrom) { params.yf = num(o.yearFrom, 0); where.push('year >= {yf:UInt16}'); }
  if (o.yearTo) { params.yt = num(o.yearTo, 3000); where.push('year <= {yt:UInt16}'); }
  if (o.area) { params.area = String(o.area); where.push('area = {area:String}'); }
  if (o.field) { params.field = String(o.field); where.push('field = {field:String}'); }
  if (o.lang) { params.lang = String(o.lang); where.push('lang = {lang:String}'); }
  if (o.types && o.types.length) { params.types = o.types.map(String); where.push('type IN {types:Array(String)}'); }
  if (o.oaOnly) where.push('is_oa = 1');
  if (o.citableOnly !== false) where.push('is_citable = 1');                                        // default: research papers only
  if (o.hasAbstract) where.push('has_abstract = 1');
  if (o.domestic) where.push('(is_kr = 1 OR ko_ratio >= 0.3 OR in_kci = 1)');                        // by data, not by a regex on the title
  const idx = (o.indexes || []).map(x => IDX_FLAGS[String(x).toLowerCase()]).filter(Boolean);
  if (idx.length) where.push('(' + idx.map(c => `${c} = 1`).join(' OR ') + ')');
  if (o.minJif) { params.mj = num(o.minJif, 0); where.push('(jif >= {mj:Float32} OR (jif = 0 AND jif_est >= {mj:Float32}))'); }
  if (o.jifQuartile) { params.jq = String(o.jifQuartile); where.push('jif_q = {jq:String}'); }
  if (o.journalId) { params.jid = num(o.journalId, 0); where.push('journal_id = {jid:UInt64}'); }
  if (o.issn) { params.issn = String(o.issn); where.push('issn_l = {issn:String}'); }
  if (o.authorId) { params.aid = num(o.authorId, 0); where.push('has(author_ids, {aid:UInt64})'); }
  if (o.doi) { params.doi = String(o.doi).toLowerCase().replace(/^https?:\/\/(dx\.)?doi\.org\//, ''); where.push('doi = {doi:String}'); }
  const nowY = new Date().getFullYear();
  const hits = (col) => words.map((w, i) => (isCjk(w) ? `positionUTF8(lowerUTF8(${col}), {w_${i}:String}) > 0` : `hasToken(lowerUTF8(${col}), {w_${i}:String})`));
  const frac = arr => (arr.length ? `(${arr.map(x => `toUInt8(${x})`).join(' + ')}) / ${arr.length}` : '0');
  const phraseScore = col => (phrases.length ? `(${phrases.map((_, i) => `toUInt8(positionUTF8(lowerUTF8(${col}), {p_${i}:String}) > 0)`).join(' + ')}) / ${phrases.length}` : '0');
  // transparent relevance: text match dominates; impact / recency / journal quality only order among matches
  const score = `(4 * (${frac(hits('title'))}) + 1.5 * (${frac(hits('abstract'))}) + 2.5 * (${phraseScore('title')}) + 1 * (${phraseScore('abstract')})
      + 0.8 * least(fwci, 5) / 5 + 0.5 * cite_pct / 100 + 0.4 * greatest(0, 1 - (${nowY} - year) / 15)
      + 0.4 * multiIf(jif_q = 'Q1', 1, jif_q = 'Q2', 0.6, jif_q = 'Q3', 0.3, in_scie + in_ssci > 0, 0.3, 0) + 0.2 * (in_scopus + in_kci > 0) - 1.5 * (meta_conflict > 0))`;   // records whose DOI/journal look mis-assigned sink instead of borrowing a journal's prestige
  // Stage-1 score: identical except that the abstract terms are dropped.  Every stage-1 row already has all words in the TITLE, so the
  // abstract adds little, and reading `abstract` for the scattered matches meant reading the whole column (measured: 30 s vs 5 s).
  const scoreT = `(4 * (${frac(hits('title'))}) + 2.5 * (${phraseScore('title')})
      + 0.8 * least(fwci, 5) / 5 + 0.5 * cite_pct / 100 + 0.4 * greatest(0, 1 - (${nowY} - year) / 15)
      + 0.4 * multiIf(jif_q = 'Q1', 1, jif_q = 'Q2', 0.6, jif_q = 'Q3', 0.3, in_scie + in_ssci > 0, 0.3, 0) + 0.2 * (in_scopus + in_kci > 0) - 1.5 * (meta_conflict > 0))`;
  const order = SORTS[o.sort] || SORTS.relevance;
  params.lim = Math.min(Math.max(num(o.limit, 50), 1), 200); params.off = Math.max(num(o.offset, 0), 0);
  const cols = `SELECT concat('https://openalex.org/W', toString(wid)) AS id, wid, doi, title, abstract, year, type, lang, cited, fwci, cite_pct, is_citable, is_oa, oa_license, pdf_url,
      landing_url, if(doi != '', concat('https://doi.org/', doi), landing_url) AS doi_url, pmid, area, field, subfield, topic, keywords, journal, journal_id, issn_l, publisher,
      in_scie, in_ssci, in_ahci, in_esci, in_scopus, in_kci, in_doaj, jif, jif_q, jif_est, j_h, first_author, author_names, n_authors, countries, is_kr, tier, meta_conflict,
      round(${score}, 4) AS score`;
  const sql = `${cols}
    FROM ${DB}.lit_papers FINAL WHERE ${where.join(' AND ')} ORDER BY ${order}, wid LIMIT {off:UInt32}, {lim:UInt32} FORMAT JSONEachRow`;
  // staged relevance search: stage 1 = title matches, stage 2 = abstract-only matches (used only to fill the page)
  const base = where.filter(x => !textAny.includes(x));
  const staged = textTitle.length > 0 && (o.sort || 'relevance') === 'relevance';
  const CAP = 100001;
  const titleWhere = [...base, ...textTitle].join(' AND '), absWhere = [...base, ...textAny, `NOT (${textTitle.join(' AND ')})`].join(' AND ');
  const stage1 = `${cols.split(score).join(scoreT)}
    FROM ${DB}.lit_papers FINAL WHERE ${titleWhere} ORDER BY ${order}, wid LIMIT {off:UInt32}, {lim:UInt32} FORMAT JSONEachRow`;
  const stage2 = `${cols}
    FROM ${DB}.lit_papers FINAL WHERE ${absWhere} ORDER BY ${order}, wid LIMIT {off2:UInt32}, {lim2:UInt32} FORMAT JSONEachRow`;
  const count1 = `SELECT count() AS total FROM (SELECT 1 FROM ${DB}.lit_papers FINAL WHERE ${titleWhere} LIMIT ${CAP}) FORMAT JSONEachRow`;
  const count2 = `SELECT count() AS total FROM (SELECT 1 FROM ${DB}.lit_papers FINAL WHERE ${absWhere} LIMIT ${CAP}) FORMAT JSONEachRow`;
  const countSql = `SELECT count() AS total FROM ${DB}.lit_papers FINAL WHERE ${where.join(' AND ')} FORMAT JSONEachRow`;
  // facets of a staged search describe the title matches (fast, topically tight); otherwise the whole match set
  const facetSql = `SELECT year, area, lang, in_scie + in_ssci > 0 AS sci, in_scopus AS scopus, in_kci AS kci, is_oa, count() AS n, sum(cited) AS cited_sum
    FROM ${DB}.lit_papers FINAL WHERE ${staged ? titleWhere : where.join(' AND ')} GROUP BY year, area, lang, sci, scopus, kci, is_oa FORMAT JSONEachRow`;
  return { sql, countSql, facetSql, staged, stage1, stage2, count1, count2, facetBasis: staged ? 'title' : 'all', params: Object.fromEntries(Object.entries(params).filter(([k]) => k !== 'words' && k !== 'phrases')) };
}

export function buildNetwork(wids) {
  const ids = wids.map(w => `https://openalex.org/W${Number(w)}`);
  return { params: { ids },
    edgesSql: `SELECT toUInt64OrZero(substring(id, 23)) AS citing, toUInt64OrZero(substring(r, 23)) AS cited
      FROM (SELECT id, referenced_works FROM ${SRC}.papers_v2 WHERE id IN {ids:Array(String)} ORDER BY ingested_at DESC LIMIT 1 BY id) ARRAY JOIN referenced_works AS r
      WHERE has({ids:Array(String)}, r) FORMAT JSONEachRow`,
    couplingSql: `SELECT toUInt64OrZero(substring(a.id, 23)) AS a_wid, toUInt64OrZero(substring(b.id, 23)) AS b_wid, length(arrayIntersect(a.referenced_works, b.referenced_works)) AS shared_refs
      FROM (SELECT id, referenced_works FROM ${SRC}.papers_v2 WHERE id IN {ids:Array(String)} ORDER BY ingested_at DESC LIMIT 1 BY id) a
      CROSS JOIN (SELECT id, referenced_works FROM ${SRC}.papers_v2 WHERE id IN {ids:Array(String)} ORDER BY ingested_at DESC LIMIT 1 BY id) b
      WHERE a.id < b.id AND shared_refs >= 2 ORDER BY shared_refs DESC LIMIT 2000 FORMAT JSONEachRow` };
}

// ClickHouse HTTP: parameter values are ESCAPED TEXT (backslash, tab, newline, CR must be escaped)
const esc = x => String(x).replace(/\\/g, '\\\\').replace(/\t/g, '\\t').replace(/\n/g, '\\n').replace(/\r/g, '\\r');
const quote = x => "'" + String(x).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\t/g, '\\t').replace(/\r/g, '\\r') + "'";
const paramValue = (v) => (Array.isArray(v) ? '[' + v.map(quote).join(',') + ']' : esc(v));

async function ch(sql, params, signal) {
  const url = new URL(process.env.CLICKHOUSE_URL || 'http://127.0.0.1:8123');
  url.searchParams.set('query', sql);
  url.searchParams.set('default_format', 'JSONEachRow');
  url.searchParams.set('max_execution_time', process.env.LLB_TIMEOUT_S || '15');
  url.searchParams.set('max_result_rows', '100000');
  for (const [k, v] of Object.entries(params)) url.searchParams.set('param_' + k, paramValue(v));
  const headers = {};
  if (process.env.CLICKHOUSE_USER) headers['Authorization'] = 'Basic ' + Buffer.from(process.env.CLICKHOUSE_USER + ':' + (process.env.CLICKHOUSE_PASSWORD || '')).toString('base64');
  const res = await fetch(url, { method: 'POST', headers, signal });
  const text = await res.text();
  if (!res.ok) throw new Error('LLB ClickHouse ' + res.status + ': ' + text.slice(0, 300));
  return text.trim() ? text.trim().split('\n').map((l) => JSON.parse(l)) : [];
}

/** Search the local literature base.  Throws on failure — the caller must SAY that the local corpus was not used. */
export async function searchLlb(opts = {}) {
  const t0 = Date.now();
  const r = await runSearch(buildSearch(opts), (sql, params) => ch(sql, params));
  return { source: 'LLB', ms: Date.now() - t0, ...r };
}
export async function facetsLlb(opts = {}) { const s = buildSearch(opts); return ch(s.facetSql, s.params); }
export async function networkLlb(wids) {
  const n = buildNetwork(wids);
  const [citations, coupling] = await Promise.all([ch(n.edgesSql, n.params), ch(n.couplingSql, n.params)]);
  return { citations, coupling };
}
