// ════════════════════════════════════════════════════════════════════════
//  RDOS v13 — 구조 엔진 확장 논문 유형 (9종)
//  ----------------------------------------------------------------------
//  첨부 "범주별 유형별 논문정리(.xlsx)" 및 각 유형별 "거시·미시 구조 완전가이드(.docx)"
//  를 분석·반영하여, 기존 24개 유형과 동일한 Chapter[] 포맷으로 정리한 확장 유형.
//    · 디지털·계산:  dh(디지털인문학) ds(데이터사이언스) na(네트워크분석) sim(시뮬레이션)
//    · 철학·해석:    phil(철학적논증) herm(해석학) phen(현상학)
//    · 학제간·미래:  conv(융합연구) fut(미래예측)
//  대표 서적: IPA(Smith) · Merleau-Ponty · Gadamer · Ricoeur · Weston · Graff/Birkenstein ·
//             Law · Banks · Scott · Borgatti · Provost/Fawcett · Hastie · Burdick · Rockwell ·
//             Repko/Szostak · Frodeman · Linstone/Turoff(Delphi) · Lindgren(Scenario)
// ════════════════════════════════════════════════════════════════════════
import type { Chapter } from "@/lib/research-data";

const C = {
  intro: "#6c8cff", theory: "#ec4899", lit: "#a78bfa", method: "#f87171",
  midA: "#f59e0b", midB: "#14b8a6", midC: "#10b981", midD: "#06b6d4",
  results: "#fb923c", disc: "#e879f9", concl: "#38bdf8",
};

/* ── ㉛ 현상학 연구 (Phenomenology / IPA) ───────────────────────────────── */
export const CHAPTERS_PHEN: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"살아있는 경험의 중요성 · 현상학적 접근 정당화", question:"왜 이 경험을 현상학으로 탐구하는가?",
    macro:"경험 현상 제기 → 기존 방법의 한계 → 현상학적 접근의 적합성 → 개방형 탐구 질문",
    micro:["P1: 탐구할 살아있는 경험(lived experience) 제시","P2: 기존 연구가 그 경험의 의미를 포착하지 못한 공백","P3: 현상학(IPA/기술적/해석적)이 적합한 이유","P4: 연구자 위치성·전제 괄호치기(epoché) 예고","P5: 개방형 탐구 질문(어떻게/무엇을 의미)"],
    goodPatterns:["경험의 의미성 강조","현상학적 전통 선택 명시","개방형 질문","위치성 선언"],
    badPatterns:["가설·변수 설정","현상 수치화","폐쇄형 질문(~인가?)","방법 정당화 누락"] },
  { num:"CH.02", title:"이론적 배경 (Phenomenological Tradition)", color:C.theory,
    desc:"현상학적 전통과 분석 렌즈 확립", question:"어떤 현상학적 렌즈로 보는가?",
    macro:"전통 선택(Husserl/Heidegger/Merleau-Ponty) → 핵심 개념 → 분석 렌즈 → 연구 정렬",
    micro:["현상학적 전통과 철학적 토대","지향성·체현(embodiment)·생활세계 등 핵심 개념","기술적 vs 해석적 현상학의 선택 논거","개념과 본 연구의 정렬"],
    goodPatterns:["전통과 개념 일치","Merleau-Ponty 체현 활용","개념의 조작적 사용"],
    badPatterns:["전통 혼용","개념 나열만","철학과 분석 단절"] },
  { num:"CH.03", title:"선행 연구 (Literature Review)", color:C.lit,
    desc:"경험에 관한 기존 지형도 · 방법론적 공백", question:"기존 연구는 이 경험을 어떻게 다뤘는가?",
    macro:"경험 관련 선행연구 지형 → 방법론적 한계 → 현상학적 공백 논거",
    micro:["탐구 경험에 관한 선행연구 지형도","주로 양적/관찰적 접근의 한계","현상학적 1인칭 관점의 부재","본 연구의 기여 위치 설정"],
    goodPatterns:["방법론적 한계에서 공백 도출","경험 중심 정리","과잉 일반화 회피"],
    badPatterns:["주제만 나열","공백 막연","연구자 해석 선개입"] },
  { num:"CH.04", title:"연구방법 (Methodology)", color:C.method,
    desc:"현상학적 정당화 + 절차적 투명성", question:"어떻게 경험을 수집·분석했는가?",
    macro:"방법 정당화 → 목적 표집 → 반구조화 심층면담 → 단계적 분석 절차",
    micro:["IPA/기술적 분석 설계와 정당화","목적 표집(동질적 소표본)·참여자 기술","반구조화 심층 면담 절차","축어록→창발적 주제→상위 주제 분석 단계","신뢰성(투명성·감사추적·성찰성)"],
    goodPatterns:["분석 단계 투명 기술","소표본 동질성 논거","성찰성 보고"],
    badPatterns:["표집 근거 없음","분석 절차 블랙박스","표본 대표성 주장"] },
  { num:"CH.05", title:"연구결과 (Findings)", color:C.results,
    desc:"주제 구조의 두꺼운 기술(thick description)", question:"경험은 어떤 의미 구조를 가지는가?",
    macro:"상위 주제 → 하위 주제 → 참여자 인용 → 해석적 기술",
    micro:["주제 구조(상위/하위 주제) 제시","참여자 축어 인용으로 근거화","두꺼운 기술로 경험의 질감 전달","해석과 사례의 균형"],
    goodPatterns:["인용+해석 직조","주제 간 긴장 드러냄","경험의 생생함"],
    badPatterns:["인용 없는 요약","주제 단순 분류","과잉 일반화"] },
  { num:"CH.06", title:"논의 (Discussion)", color:C.disc,
    desc:"주제 구조의 이론적·실천적 함의", question:"이 의미 구조가 시사하는 것은?",
    macro:"결과 재진술 → 현상학적·이론적 해석 → 실천 함의 → 한계·성찰",
    micro:["주제 구조를 더 넓은 맥락에 위치","현상학적 문헌·이론과의 대화","실천적 시사점","방법적 한계와 연구자 성찰"],
    goodPatterns:["이론과 대화","경험→함의 연결","성찰적 한계"],
    badPatterns:["결과 반복","일반화된 처방","한계 회피"] },
  { num:"CH.07", title:"결론 (Conclusion)", color:C.concl,
    desc:"탐구 질문에 대한 현상학적 답변", question:"이 연구가 경험에 관해 밝힌 것은?",
    macro:"질문 재호응 → 핵심 통찰 → 기여 → 후속 탐구",
    micro:["서론 탐구 질문에의 응답 선언","핵심 현상학적 통찰 요약","이해에의 기여","후속 탐구 방향"],
    goodPatterns:["질문 재호응","간명한 통찰","열린 결말"],
    badPatterns:["논의 반복","과한 일반화","새 자료 도입"] },
];

/* ── ㉚ 해석학 연구 (Hermeneutics / Gadamer·Ricoeur) ────────────────────── */
export const CHAPTERS_HERM: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"해석 대상·해석학적 문제 제기", question:"왜 이 텍스트/현상을 해석해야 하는가?",
    macro:"해석 대상 제시 → 의미의 불확정성 → 해석학적 접근 정당화 → 해석 질문",
    micro:["P1: 해석 대상(텍스트·현상·전통) 제시","P2: 기존 해석의 한계·이해의 공백","P3: 해석학적 접근(Gadamer/Ricoeur) 정당화","P4: 연구자의 선이해(Vorverständnis) 명시","P5: 해석 질문 선언"],
    goodPatterns:["선이해 명시","해석학적 순환 예고","의미 문제화"],
    badPatterns:["객관적 진리 주장","선이해 은폐","방법 정당화 누락"] },
  { num:"CH.02", title:"이론적 배경 (Hermeneutic Tradition)", color:C.theory,
    desc:"해석학적 전통과 분석 렌즈", question:"어떤 해석학으로 읽는가?",
    macro:"전통 선택 → 핵심 개념(지평융합·해석순환) → 분석 렌즈 정렬",
    micro:["철학적 해석학 전통(Gadamer)·텍스트 해석학(Ricoeur)","지평 융합·영향사·거리두기 등 개념","해석의 타당성 기준","개념과 연구 대상의 정렬"],
    goodPatterns:["지평융합 활용","거리두기와 전유 균형","개념 일관성"],
    badPatterns:["전통 절충","개념 장식적 사용","순환 무시"] },
  { num:"CH.03", title:"선행 연구 / 해석 지형도 (Literature Review)", color:C.lit,
    desc:"기존 해석들의 지형과 한계", question:"이 대상은 어떻게 해석되어 왔는가?",
    macro:"해석사 정리 → 지배적 해석의 한계 → 본 해석의 자리",
    micro:["대상에 관한 해석 전통·계보","지배적 해석과 그 전제","해석의 공백·긴장 지점","본 연구 해석의 위치"],
    goodPatterns:["해석사 비판적 정리","긴장 지점 포착","겸손한 위치설정"],
    badPatterns:["연구 나열","해석 무비판 수용","공백 막연"] },
  { num:"CH.04", title:"텍스트·현상 분석 (Textual Analysis)", color:C.method,
    desc:"해석학적 순환을 통한 정밀 독해", question:"부분과 전체를 어떻게 읽었는가?",
    macro:"부분 정독 → 전체 맥락 → 해석학적 순환 → 의미 층위 발굴",
    micro:["분석 단위와 정독 절차","부분↔전체의 해석학적 순환","역사적·맥락적 지평 복원","의미의 다층성 발굴"],
    goodPatterns:["순환 명시적 수행","맥락 복원","근거 텍스트 제시"],
    badPatterns:["임의적 인용","맥락 무시","절차 불투명"] },
  { num:"CH.05", title:"해석적 논증 (Interpretive Argument)", color:C.results,
    desc:"해석의 정당화와 설득", question:"왜 이 해석이 더 타당한가?",
    macro:"해석 명제 → 텍스트 근거 → 경쟁 해석 비교 → 설득력 확립",
    micro:["핵심 해석 명제 제시","텍스트·맥락 근거 제시","경쟁 해석과의 비교 우위","해석의 정합성·풍부성 논거"],
    goodPatterns:["근거-해석 직조","경쟁 해석 대조","정합성 논거"],
    badPatterns:["근거 없는 단정","경쟁 해석 무시","과잉 해석"] },
  { num:"CH.06", title:"논의 (Discussion)", color:C.disc,
    desc:"해석의 함의와 적용", question:"이 해석은 무엇을 바꾸는가?",
    macro:"해석 재진술 → 이론적 기여 → 적용 가능성 → 한계",
    micro:["해석의 더 넓은 함의","해석학적·이론적 기여","현재적 적용(전유)","해석의 한계·잠정성"],
    goodPatterns:["전유 명시","기여 구체화","잠정성 인정"],
    badPatterns:["해석 반복","보편 진리화","한계 회피"] },
  { num:"CH.07", title:"결론 (Conclusion)", color:C.concl,
    desc:"해석 질문에의 응답·열린 지평", question:"이 해석이 연 새 지평은?",
    macro:"질문 재호응 → 핵심 해석 요약 → 기여 → 후속 해석",
    micro:["해석 질문에의 응답","핵심 해석 요약","이해 지평 확장의 기여","후속 해석 과제"],
    goodPatterns:["지평 확장 선언","간명 요약","열린 결말"],
    badPatterns:["논의 반복","최종 진리 선언","새 텍스트 도입"] },
];

/* ── ㉙ 철학적 논증 (Philosophical Argument / Weston·Graff) ─────────────── */
export const CHAPTERS_PHIL: Chapter[] = [
  { num:"CH.01", title:"서론 / 문제 제기 (Introduction)", color:C.intro,
    desc:"대화로의 진입(They Say) · 논제 선언", question:"어떤 철학적 문제에 개입하는가?",
    macro:"문제·논쟁 제시(They Say) → 쟁점의 중요성 → 본 논제(I Say) → 논증 지도",
    micro:["P1: 기존 입장·논쟁 요약(They Say)","P2: 쟁점이 왜 중요한가(So What)","P3: 본 논문의 논제(Thesis) 선언","P4: 논증의 로드맵 예고"],
    goodPatterns:["They Say/I Say 진입","논제 명료","중요성 확립"],
    badPatterns:["맥락 없는 단정","논제 모호","로드맵 부재"] },
  { num:"CH.02", title:"개념 분석 / 용어 정의 (Conceptual Analysis)", color:C.theory,
    desc:"핵심 개념의 정밀 정의", question:"핵심 용어를 어떻게 규정하는가?",
    macro:"핵심 개념 식별 → 정의 제시 → 구별·경계 → 분석 도구화",
    micro:["논증의 핵심 개념 식별","명시적·정합적 정의","유사 개념과의 구별","정의의 논증적 역할"],
    goodPatterns:["정의의 명시성","반례로 경계 시험","일관 사용"],
    badPatterns:["용어 혼용","순환 정의","정의 없는 사용"] },
  { num:"CH.03", title:"중심 논증 제시 (The Main Argument)", color:C.method,
    desc:"전제→결론의 타당한 구조", question:"논증의 형식적 구조는?",
    macro:"전제 명시 → 추론 형식 → 결론 도출 → 타당성 확보",
    micro:["전제(P1, P2…)의 명시적 진술","연역/귀납/유비 등 추론 형식","결론으로의 단계적 도출","타당성·건전성 점검"],
    goodPatterns:["전제 명시","형식 일관","건전성 확보"],
    badPatterns:["숨은 전제","비약","형식 오류"] },
  { num:"CH.04", title:"전제 옹호 (Defending the Premises)", color:C.midB,
    desc:"각 전제의 독립적 정당화", question:"왜 각 전제를 받아들여야 하는가?",
    macro:"전제별 근거 → 직관·사례·권위 → 강도 평가",
    micro:["논쟁적 전제 식별","전제별 독립 근거(사례·원리·증언)","근거의 강도 평가","약한 전제 보강"],
    goodPatterns:["전제별 근거","사고실험 활용","근거 강도 명시"],
    badPatterns:["전제 방치","근거 빈약","권위에 호소만"] },
  { num:"CH.05", title:"반론 검토와 응답 (Objections & Replies)", color:C.results,
    desc:"가장 강한 반론을 심고 응답", question:"최강의 반론에 어떻게 답하는가?",
    macro:"반론 심기(강한 형태) → 분류(전제/추론/함의) → 세 방식의 응답",
    micro:["가장 강한 반론을 공정히 재구성","반론의 표적(전제/추론/결론) 분류","응답: 반박·수용후재정식화·구별","논제의 수정·강화"],
    goodPatterns:["반론 자비롭게 재구성","표적 명확","응답 정직"],
    badPatterns:["허수아비 반론","반론 회피","감정적 대응"] },
  { num:"CH.06", title:"대안 검토 (Exploring Alternatives)", color:C.disc,
    desc:"경쟁 입장과의 비교 우위", question:"경쟁 입장보다 나은 이유는?",
    macro:"경쟁 입장 제시 → 기준 설정 → 비교 → 본 논제의 우위",
    micro:["주요 경쟁 입장 정리","평가 기준(정합성·설명력·단순성)","기준별 비교","본 논제의 비교 우위"],
    goodPatterns:["공정한 비교","명시적 기준","우위 논거"],
    badPatterns:["대안 무시","기준 자의","우위 단정"] },
  { num:"CH.07", title:"결론 (Conclusion)", color:C.concl,
    desc:"논제 재확인·철학적 함의", question:"이 논증이 확립한 것은?",
    macro:"논제 재진술 → 논증 요약 → 철학적 함의 → 남은 문제",
    micro:["논제와 핵심 논증 재진술","무엇이 확립되었는가","철학적·실천적 함의","미해결 문제·후속 논의"],
    goodPatterns:["논제 재확인","함의 명시","겸손한 한계"],
    badPatterns:["과잉 일반화","논증 반복","새 논증 도입"] },
];

/* ── ㉘ 시뮬레이션 연구 (Simulation / Law·Banks) ───────────────────────── */
export const CHAPTERS_SIM: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"문제 정의 · 시뮬레이션 정당화", question:"왜 시뮬레이션이 필요한가?",
    macro:"실세계 문제 → 분석적 접근의 한계 → 시뮬레이션의 적합성 → 연구 목표",
    micro:["P1: 대상 시스템과 문제 정의","P2: 해석적/실험적 접근의 한계","P3: 시뮬레이션(DES/ABM/MC) 적합성","P4: 연구 목표·성능 지표"],
    goodPatterns:["문제 범위 명확","방법 선택 정당화","지표 사전 정의"],
    badPatterns:["목적 모호","방법 정당화 없음","지표 사후 설정"] },
  { num:"CH.02", title:"이론적 배경 / 문헌 검토 (Background)", color:C.theory,
    desc:"도메인 이론 + 시뮬레이션 선행연구", question:"어떤 이론·모델 위에 서는가?",
    macro:"도메인 이론 → 기존 모델 → 방법론 비교 → 본 모델 위치",
    micro:["대상 도메인의 이론·법칙","기존 시뮬레이션 연구","모델링 패러다임 비교","본 연구 모델의 차별점"],
    goodPatterns:["도메인+방법 양면 검토","모델 비교","차별점 명시"],
    badPatterns:["방법만 검토","도메인 무시","차별점 모호"] },
  { num:"CH.03", title:"시스템 기술 및 개념 모델 (Conceptual Model)", color:C.midA,
    desc:"실세계 → 개념 모델 추상화", question:"시스템을 어떻게 추상화했는가?",
    macro:"시스템 경계 → 엔티티·속성·이벤트 → 가정·단순화 → 개념 모델",
    micro:["시스템 경계와 범위","엔티티·속성·상태·이벤트 정의","핵심 가정과 단순화 논거","개념 모델 다이어그램"],
    goodPatterns:["가정 명시","경계 명확","개념도 제공"],
    badPatterns:["가정 은폐","범위 모호","추상화 비약"] },
  { num:"CH.04", title:"입력 모델링 및 모델 구현 (Input & Implementation)", color:C.method,
    desc:"입력 분포 적합 + 코드 구현", question:"입력과 모델을 어떻게 구현했는가?",
    macro:"자료 수집 → 분포 적합·적합도 검정 → 코딩·난수 → 재현 정보",
    micro:["입력 자료 수집·정제","확률 분포 적합 및 적합도 검정","모델 코드 구현·난수 생성","플랫폼·시드·재현 정보"],
    goodPatterns:["분포 적합도 보고","시드 공개","구현 검증"],
    badPatterns:["임의 분포 가정","재현 정보 누락","난수 처리 불명"] },
  { num:"CH.05", title:"검증 및 타당화 (Verification & Validation)", color:C.midB,
    desc:"V&V — 신뢰성의 핵심", question:"모델이 옳게·맞게 작동하는가?",
    macro:"검증(코드 정확) → 타당화(실세계 부합) → 보정 → 신뢰 구축",
    micro:["검증(Verification): 코드가 개념모델과 일치","타당화(Validation): 실데이터·전문가 대조","보정(Calibration)과 민감도 점검","신뢰성 근거 제시"],
    goodPatterns:["V&V 분리 보고","실데이터 대조","민감도 분석"],
    badPatterns:["V&V 생략","검증=타당화 혼동","보정 과적합"] },
  { num:"CH.06", title:"실험 설계 및 출력 분석 (Design & Output)", color:C.midC,
    desc:"실험 설계 + 통계적 출력 분석", question:"실험을 어떻게 설계·분석했는가?",
    macro:"요인·시나리오 설계 → 워밍업·반복수 → 신뢰구간 → 시나리오 비교",
    micro:["실험 요인·시나리오 설계(DOE)","워밍업 기간·반복(replications) 수 결정","출력의 신뢰구간 추정","시나리오 간 통계 비교"],
    goodPatterns:["반복수 근거","워밍업 처리","CI 보고"],
    badPatterns:["단일 실행","과도기 미처리","CI 누락"] },
  { num:"CH.07", title:"결과 (Results)", color:C.results,
    desc:"성능 지표의 객관적 보고", question:"무엇이 관측되었는가?",
    macro:"지표별 결과 → 시나리오 비교 → 표·그림 → 사실 보고",
    micro:["성능 지표별 정량 결과","시나리오·요인별 비교","표·그래프 시각화","해석 없는 사실 제시"],
    goodPatterns:["지표 일관 보고","불확실성 표기","해석 분리"],
    badPatterns:["체리피킹","불확실성 은폐","해석 혼입"] },
  { num:"CH.08", title:"논의 (Discussion)", color:C.disc,
    desc:"결과의 의미·일반화 한계", question:"이 결과가 시사하는 것은?",
    macro:"결과 해석 → 실무 함의 → 모델 한계·일반화 경계 → 후속",
    micro:["결과의 도메인적 해석","의사결정·실무 함의","모델 가정의 한계와 일반화 경계","후속 모델링 방향"],
    goodPatterns:["가정→한계 연결","실무 함의","경계 명시"],
    badPatterns:["과잉 일반화","한계 축소","결과 반복"] },
  { num:"CH.09", title:"결론 (Conclusion)", color:C.concl,
    desc:"기여·실용적 가치", question:"이 시뮬레이션의 기여는?",
    macro:"목표 재호응 → 핵심 발견 → 방법·실무 기여 → 향후 연구",
    micro:["연구 목표 달성 요약","핵심 발견 정리","방법론적·실용적 기여","향후 확장 방향"],
    goodPatterns:["목표 재호응","기여 구체화","재현성 강조"],
    badPatterns:["논의 반복","기여 모호","한계 무시"] },
];

/* ── ㉗ 네트워크 분석 (Network Analysis / Scott·Borgatti) ───────────────── */
export const CHAPTERS_NA: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"관계적 관점의 문제 제기", question:"왜 관계 구조로 보아야 하는가?",
    macro:"현상 제기 → 속성중심 접근의 한계 → 관계적(네트워크) 관점 → 연구 질문",
    micro:["P1: 대상 현상과 관계적 성격","P2: 개체 속성 중심 접근의 한계","P3: 네트워크 관점의 기여","P4: 연구 질문·가설"],
    goodPatterns:["관계적 관점 정당화","현상-구조 연결","질문 명확"],
    badPatterns:["속성 환원","관점 정당화 없음","질문 모호"] },
  { num:"CH.02", title:"관련 연구 (Related Work)", color:C.lit,
    desc:"네트워크 선행연구 지형", question:"기존 네트워크 연구는 무엇을 밝혔나?",
    macro:"관련 연구 정리 → 측정·방법 동향 → 공백 도출",
    micro:["주제 영역 네트워크 선행연구","사용된 지표·방법 동향","상충·미해결 지점","본 연구의 공백·기여"],
    goodPatterns:["방법 동향 정리","공백 도출","기여 명시"],
    badPatterns:["나열식","방법 무비판","공백 막연"] },
  { num:"CH.03", title:"이론적 배경 / 개념적 기반 (Theory)", color:C.theory,
    desc:"네트워크 이론·개념 정의", question:"어떤 네트워크 이론에 기반하는가?",
    macro:"이론(약한 연결·구조적 공백 등) → 핵심 지표 개념 → 가설 정렬",
    micro:["네트워크 이론(SNA/그래프 이론)","중심성·군집·구조적 공백 등 개념 정의","이론→가설 연결","측정 수준(노드/엣지/전체)"],
    goodPatterns:["이론-지표 연결","개념 조작화","측정 수준 명시"],
    badPatterns:["지표 나열","이론 단절","수준 혼동"] },
  { num:"CH.04", title:"데이터 및 네트워크 구성 (Data & Construction)", color:C.method,
    desc:"노드·엣지 정의와 경계 설정", question:"네트워크를 어떻게 구성했는가?",
    macro:"자료원 → 노드·엣지 정의 → 경계 규정 → 가중·방향 처리",
    micro:["자료원·수집 절차","노드·엣지의 조작적 정의","네트워크 경계(boundary specification)","방향성·가중치·시간 처리"],
    goodPatterns:["경계 규정 명시","엣지 정의 투명","결측 처리"],
    badPatterns:["경계 임의","엣지 모호","결측 무시"] },
  { num:"CH.05", title:"분석 방법 (Methods)", color:C.midA,
    desc:"지표 계산·모형(ERGM 등)", question:"어떤 분석을 수행했는가?",
    macro:"기술 지표 → 군집·역할 분석 → 추론 모형(ERGM/SAOM) → 통계 검정",
    micro:["중심성·밀도·경로 등 기술 지표","커뮤니티·블록모델 분석","추론 모형(ERGM/SAOM) 적용","유의성·강건성 검정"],
    goodPatterns:["지표 선택 근거","추론 모형 명시","강건성 점검"],
    badPatterns:["지표 남용","모형 가정 무시","검정 누락"] },
  { num:"CH.06", title:"결과 (Results)", color:C.results,
    desc:"구조 패턴의 객관적 보고", question:"어떤 구조가 발견되었나?",
    macro:"기술 결과 → 시각화 → 모형 추정치 → 가설 대응",
    micro:["네트워크 기술 통계","그래프 시각화·핵심 노드","모형 추정 결과","가설별 대응"],
    goodPatterns:["시각화+수치","추정 불확실성","가설 대응"],
    badPatterns:["시각화만","불확실성 누락","해석 혼입"] },
  { num:"CH.07", title:"논의 및 결론 (Discussion & Conclusion)", color:C.concl,
    desc:"구조의 의미·기여·한계", question:"이 구조가 의미하는 것은?",
    macro:"결과 해석 → 이론 기여 → 한계(경계·인과) → 후속·결론",
    micro:["구조 패턴의 이론적 해석","기여와 실천 함의","경계·인과 추론의 한계","후속 연구와 결론 선언"],
    goodPatterns:["구조→의미 연결","인과 한계 명시","기여 구체화"],
    badPatterns:["상관=인과","경계 효과 무시","결과 반복"] },
];

/* ── ㉖ 데이터 사이언스 (Data Science / Provost·Hastie) ─────────────────── */
export const CHAPTERS_DS: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"문제 정의 · 데이터 기반 동기", question:"어떤 예측/추론 문제를 푸는가?",
    macro:"비즈니스/과학 문제 → 데이터 기회 → 과제 정식화 → 기여 요약",
    micro:["P1: 문제 정의와 동기","P2: 데이터로 풀 수 있는 이유","P3: 과제 정식화(분류/회귀/군집)","P4: 기여(Contributions) 요약"],
    goodPatterns:["문제→과제 매핑","기여 명시","평가지표 예고"],
    badPatterns:["문제 모호","과제 불명확","기여 누락"] },
  { num:"CH.02", title:"관련 연구 (Related Work)", color:C.lit,
    desc:"기법·벤치마크 선행연구", question:"기존 방법은 무엇을 했나?",
    macro:"관련 기법 → 벤치마크·SOTA → 한계 → 본 연구 위치",
    micro:["관련 방법·모델 계보","벤치마크·SOTA 정리","기존 한계(일반화·해석성)","본 연구의 차별점"],
    goodPatterns:["SOTA 대비","한계 도출","차별점 명시"],
    badPatterns:["나열식","비교 부재","차별점 모호"] },
  { num:"CH.03", title:"이론적 배경 / 수학적 기반 (Foundations)", color:C.theory,
    desc:"모델의 수학적 정식화", question:"방법의 수학적 토대는?",
    macro:"문제 정식화 → 손실·목적함수 → 모델 가정 → 일반화 이론",
    micro:["기호·문제의 수학적 정식화","목적함수·손실 정의","모델 가정(독립성·분포)","편향-분산·일반화 이론"],
    goodPatterns:["정식화 엄밀","가정 명시","일반화 논의"],
    badPatterns:["수식 장식","가정 은폐","과적합 무시"] },
  { num:"CH.04", title:"데이터 및 방법론 (Data & Methodology)", color:C.method,
    desc:"데이터 파이프라인 + 실험 프로토콜", question:"데이터·실험을 어떻게 설계했나?",
    macro:"데이터 기술 → 전처리·피처 → 모델·하이퍼파라미터 → 평가 프로토콜",
    micro:["데이터셋 기술·EDA·누수 점검","전처리·피처 엔지니어링","모델·하이퍼파라미터 탐색","교차검증·평가 지표·분할 전략"],
    goodPatterns:["데이터 누수 차단","CV 설계","지표 정당화"],
    badPatterns:["테스트 누수","단일 분할","지표 임의"] },
  { num:"CH.05", title:"실험 결과 (Experimental Results)", color:C.results,
    desc:"정량 비교 + 통계적 엄밀성", question:"성능은 어떠한가?",
    macro:"베이스라인 대비 → 지표별 결과 → 통계 검정 → 절제 연구(ablation)",
    micro:["베이스라인·SOTA 대비 결과","지표별 성능과 분산","유의성·신뢰구간","절제 연구(ablation)·오류 분석"],
    goodPatterns:["베이스라인 공정","분산·CI 보고","ablation 제시"],
    badPatterns:["체리피킹","분산 누락","불공정 비교"] },
  { num:"CH.06", title:"논의 (Discussion)", color:C.disc,
    desc:"해석·일반화·한계·윤리", question:"결과가 시사하는 바와 한계는?",
    macro:"결과 해석 → 일반화·전이 → 해석가능성·윤리 → 한계",
    micro:["결과의 의미·일반화 범위","분포 변화·전이 가능성","해석가능성·공정성·윤리","한계와 위협 요인"],
    goodPatterns:["일반화 경계","윤리 고려","한계 정직"],
    badPatterns:["과잉 일반화","윤리 무시","한계 회피"] },
  { num:"CH.07", title:"결론 (Conclusion)", color:C.concl,
    desc:"기여·재현성·향후", question:"이 연구의 기여와 다음은?",
    macro:"문제 재호응 → 핵심 결과 → 기여·재현성 → 향후 연구",
    micro:["문제·기여 재진술","핵심 결과 요약","코드·데이터 공개·재현성","향후 연구 방향"],
    goodPatterns:["재현성 강조","기여 구체화","향후 명확"],
    badPatterns:["결과 반복","재현 정보 누락","기여 모호"] },
];

/* ── ㉕ 디지털 인문학 (Digital Humanities / Burdick·Rockwell) ───────────── */
export const CHAPTERS_DH: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"인문학 질문 + 계산적 접근의 만남", question:"인문학 질문에 왜 디지털 방법인가?",
    macro:"인문학적 질문 → 전통적 접근의 한계 → 계산적 방법의 기여 → 연구 질문",
    micro:["P1: 인문학적 문제·해석 질문","P2: 근접 독해(close reading)의 한계·규모 문제","P3: 원거리 독해(distant reading)·계산 방법의 기여","P4: 연구 질문과 데이터 범위"],
    goodPatterns:["질문 우선·방법 종속","규모 논거","해석-계산 결합"],
    badPatterns:["방법 과시","질문 부재","도구 나열"] },
  { num:"CH.02", title:"이론적 배경 (Theoretical Background)", color:C.theory,
    desc:"인문학 이론 + DH 방법론 담론", question:"어떤 이론·방법 담론에 서는가?",
    macro:"도메인 이론 → DH 방법론 계보 → 비판적 위치 설정",
    micro:["대상 분야의 인문학 이론","원거리 독해·문화분석 등 DH 담론","계산 방법의 인식론적 전제","비판적 디지털 인문학 관점"],
    goodPatterns:["이론+방법 결합","전제 성찰","비판적 위치"],
    badPatterns:["방법만 서술","전제 무성찰","이론 단절"] },
  { num:"CH.03", title:"연구 방법론 (Digital Methods)", color:C.method,
    desc:"디지털 방법의 선택과 정당화", question:"어떤 계산 방법을 왜 쓰는가?",
    macro:"방법 선택(텍스트마이닝/GIS/네트워크) → 정당화 → 절차 → 한계 인식",
    micro:["계산 방법 선택과 인문학적 정당화","분석 파이프라인 절차","도구·라이브러리 명시","방법의 해석적 한계 인식"],
    goodPatterns:["방법 정당화","절차 투명","한계 자각"],
    badPatterns:["방법 임의","절차 불명","과신"] },
  { num:"CH.04", title:"코퍼스 구축 및 도구 적용 (Corpus & Tools)", color:C.midA,
    desc:"데이터화(datafication)와 도구 적용", question:"자료를 어떻게 데이터로 만들었나?",
    macro:"자료 선정 → 디지털화·정제 → 메타데이터·주석 → 도구 적용",
    micro:["코퍼스·자료 선정 기준","디지털화(OCR/전사)·정제","메타데이터·주석 스키마","분석 도구 적용·파라미터"],
    goodPatterns:["선정 기준 명시","정제 투명","메타데이터 문서화"],
    badPatterns:["대표성 무시","정제 은폐","주석 불명"] },
  { num:"CH.05", title:"분석 및 발견 (Analysis & Findings)", color:C.results,
    desc:"계산 결과 + 인문학적 해석", question:"무엇을 발견했고 어떻게 읽는가?",
    macro:"계산 결과(시각화) → 패턴 → 근접 독해로 검증 → 해석",
    micro:["계산 결과·시각화 제시","발견된 패턴·이상치","근접 독해로의 회귀(검증)","인문학적 해석과 의미화"],
    goodPatterns:["원거리+근접 결합","시각화 해석","사례 검증"],
    badPatterns:["수치 나열","해석 부재","시각화 오독"] },
  { num:"CH.06", title:"논의 (Discussion)", color:C.disc,
    desc:"해석의 함의·방법 성찰", question:"발견이 인문학에 무엇을 더하나?",
    macro:"발견 해석 → 분야 기여 → 방법론적 성찰 → 한계",
    micro:["발견의 인문학적 함의","분야 지식에의 기여","계산 방법의 성찰(편향·환원)","해석의 한계와 잠정성"],
    goodPatterns:["기여 구체화","방법 성찰","한계 인정"],
    badPatterns:["기술 결정론","성찰 부재","과잉 일반화"] },
  { num:"CH.07", title:"결론 (Conclusion)", color:C.concl,
    desc:"기여·데이터 공개·후속", question:"이 연구의 기여와 유산은?",
    macro:"질문 재호응 → 핵심 발견 → 기여·데이터 공개 → 후속",
    micro:["연구 질문에의 응답","핵심 발견 요약","데이터·코드 공개와 기여","후속 연구·방법 확장"],
    goodPatterns:["공개·재사용","기여 명시","후속 명확"],
    badPatterns:["발견 반복","공개 누락","기여 모호"] },
];

/* ── ㉜ 융합 연구 (Interdisciplinary / Repko·Szostak·Frodeman) ──────────── */
export const CHAPTERS_CONV: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"단일 분야 초과 문제 제기", question:"왜 분야 통합이 필요한가?",
    macro:"문제의 복잡성(분야 초과) → 필요한 분야 예고 → 통합 목표 → 연구 질문",
    micro:["P1: 문제의 복잡성이 단일 분야를 초과함","P2: 어떤 분야들이 필요한지 예고","P3: 통합으로 달성할 더 포괄적 이해","P4: 융합 연구 질문 선언"],
    goodPatterns:["복잡성 논거","분야 필요성 예고","통합 목표 명시"],
    badPatterns:["다학문 나열","통합 목표 부재","질문 모호"] },
  { num:"CH.02", title:"이론·개념적 배경 (Theoretical Background)", color:C.theory,
    desc:"관련 분야 이론 매핑", question:"어떤 분야 이론들을 동원하는가?",
    macro:"관련 분야 확인 → 각 분야 이론·개념 → 분야 간 가정 차이 → 정렬",
    micro:["관련 분야 식별과 친숙성 확보","각 분야의 핵심 이론·개념","분야별 전제·가정의 차이","통합을 위한 개념 정렬"],
    goodPatterns:["분야별 충분한 이해","가정 차이 노출","개념 정렬"],
    badPatterns:["한 분야 편중","가정 차이 은폐","개념 충돌 방치"] },
  { num:"CH.03", title:"선행 연구 (Literature Review)", color:C.lit,
    desc:"분야 횡단적 문헌 검토", question:"각 분야는 이 문제를 어떻게 다뤘나?",
    macro:"분야별 통찰 탐색 → 횡단 정리 → 통합 공백 도출",
    micro:["각 분야에서 가장 관련된 통찰","분야 횡단적 정리","분야 간 미연결 지점","통합 연구의 공백"],
    goodPatterns:["횡단적 정리","미연결 포착","공백 도출"],
    badPatterns:["분야별 분리 나열","연결 부재","공백 막연"] },
  { num:"CH.04", title:"연구방법 (Design & Methodology)", color:C.method,
    desc:"분야 방법 + 통합 방법 이중 층위", question:"분야들을 어떻게 통합하는가?",
    macro:"분야 수준 방법 → 통합 수준 방법(공통근거 창출) → 절차 → 정당화",
    micro:["분야 수준: 각 분야 연구 방법","통합 수준: 통합 전략·공통근거 기법","통합 절차의 단계화","방법론적 정당화"],
    goodPatterns:["이중 층위 명시","통합 기법 구체화","절차 투명"],
    badPatterns:["통합 방법 부재","절차 모호","분야 방법만"] },
  { num:"CH.05", title:"분야별 심층 분석 (Disciplinary Analysis)", color:C.midA,
    desc:"각 분야 통찰의 충분한 제시", question:"각 분야는 무엇을 기여하는가?",
    macro:"분야별 통찰 도출 → 충분한 깊이 → 통합 기여 명시",
    micro:["각 분야 핵심 통찰의 심층 제시","통찰의 근거와 한계","'이 통찰이 통합에 어떻게 기여하는가' 명시","분야 간 비교 준비"],
    goodPatterns:["깊이 충분","통합 지향 서술","근거 제시"],
    badPatterns:["피상적 요약","통합 무관 서술","한 분야 편중"] },
  { num:"CH.06", title:"충돌 진단·공통 근거 (Common Ground)", color:C.midB,
    desc:"융합의 핵심 — 충돌 해소", question:"분야 간 충돌을 어떻게 해소하나?",
    macro:"충돌 확인 → 원인(개념·가정·이론) → 공통 근거 창출 기법 적용",
    micro:["분야 간 충돌(개념·가정·이론) 확인","충돌의 원인 설명","Repko의 공통근거 창출 기법(재정의·확장·조직)","공통 근거의 정당화"],
    goodPatterns:["충돌 명시적 진단","공통근거 기법 적용","정당화"],
    badPatterns:["충돌 회피","절충적 봉합","기법 부재"] },
  { num:"CH.07", title:"통합 이해 구성 (Integration)", color:C.results,
    desc:"더 포괄적 이해의 구성", question:"통합된 이해는 무엇인가?",
    macro:"공통 근거 위 통합 → 더 포괄적 모델 → 검증",
    micro:["공통 근거 위에서 통찰 통합","더 포괄적 이해·모델 구성","통합 결과의 정합성 점검","통합의 새로움 제시"],
    goodPatterns:["통합 모델 제시","정합성 점검","새로움 명시"],
    badPatterns:["단순 병치","정합성 결여","새로움 부재"] },
  { num:"CH.08", title:"논의 (Discussion)", color:C.disc,
    desc:"통합 이해의 함의·평가", question:"통합이 무엇을 바꾸는가?",
    macro:"통합 함의 → 엄밀성·통합깊이·실용성 평가 → 한계",
    micro:["통합 이해의 학문적·실천적 함의","융합 평가 기준(엄밀성·통합깊이·실용성)","통합의 한계·잔여 충돌","후속 융합 과제"],
    goodPatterns:["평가 기준 적용","함의 구체화","잔여 충돌 인정"],
    badPatterns:["함의 과장","평가 누락","한계 회피"] },
  { num:"CH.09", title:"결론 (Conclusion)", color:C.concl,
    desc:"통합 해결 선언·과정 성찰", question:"통합으로 무엇을 해결했나?",
    macro:"문제 재호응 → 통합 해결 요약 → 과정 성찰·평가 → 기여",
    micro:["서론 문제의 통합적 해결 선언","통합 결과 요약","IDR 과정의 반성적 검토","기여와 후속 방향"],
    goodPatterns:["과정 성찰","해결 선언","기여 명시"],
    badPatterns:["과정 생략","논의 반복","기여 모호"] },
];

/* ── ㉝ 미래예측 연구 (Foresight / Delphi·Scenario) ────────────────────── */
export const CHAPTERS_FUT: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"미래 불확실성·예측 필요성", question:"왜 이 영역의 미래를 예측하는가?",
    macro:"변화 압력 → 불확실성 → 예측의 필요성·목적 → 예측 질문",
    micro:["P1: 대상 영역의 변화·불확실성","P2: 의사결정상 예측의 필요성","P3: 예측 목적·시계(time horizon)","P4: 예측 질문과 범위"],
    goodPatterns:["시계 명시","불확실성 인정","목적 구체화"],
    badPatterns:["결정론적 단정","시계 모호","목적 부재"] },
  { num:"CH.02", title:"이론·개념적 배경 (Theoretical Background)", color:C.theory,
    desc:"미래연구 이론·개념", question:"어떤 미래연구 틀에 서는가?",
    macro:"미래연구 패러다임 → 핵심 개념(동인·불확실성·시나리오) → 틀 정렬",
    micro:["미래연구(Futures Studies) 패러다임","동인·메가트렌드·약신호 등 개념","예측 vs 예견(foresight) 구분","개념 틀과 본 연구 정렬"],
    goodPatterns:["패러다임 선택 명시","개념 정의","foresight 관점"],
    badPatterns:["단일 미래 가정","개념 혼용","틀 부재"] },
  { num:"CH.03", title:"선행 연구 (Literature Review)", color:C.lit,
    desc:"기존 예측·전망 검토", question:"기존 전망은 무엇을 말했나?",
    macro:"기존 예측·전망 정리 → 방법·정확성 평가 → 공백",
    micro:["영역의 기존 예측·전망","사용된 예측 방법 평가","과거 예측의 적중·실패","본 연구의 공백·기여"],
    goodPatterns:["방법 평가","적중 평가","공백 도출"],
    badPatterns:["전망 나열","방법 무비판","공백 막연"] },
  { num:"CH.04", title:"연구방법 (Methodology)", color:C.method,
    desc:"예측 방법(Delphi/시나리오 등) 설계", question:"어떤 예측 방법을 설계했나?",
    macro:"방법 선택(Delphi/시나리오/추세외삽) → 절차 → 패널·자료 → 타당성",
    micro:["예측 방법 선택과 정당화","Delphi 라운드·합의 기준 / 시나리오 절차","전문가 패널·자료원","예측의 타당성·신뢰성 확보"],
    goodPatterns:["방법 정당화","합의 기준 명시","패널 근거"],
    badPatterns:["방법 임의","합의 불명","패널 편향"] },
  { num:"CH.05", title:"현황 분석 / 환경 스캐닝 (Scanning)", color:C.midA,
    desc:"환경 스캐닝으로 현재 진단", question:"현재 환경의 신호는?",
    macro:"STEEP 스캐닝 → 트렌드·약신호 수집 → 현황 진단",
    micro:["STEEP/PESTLE 환경 스캐닝","메가트렌드·약신호 식별","현재 상태의 체계적 진단","미래 동인 후보 도출"],
    goodPatterns:["체계적 스캐닝","약신호 포착","출처 명시"],
    badPatterns:["임의 선택","트렌드 편식","근거 부재"] },
  { num:"CH.06", title:"미래 동인 분석 (Driving Forces)", color:C.midB,
    desc:"핵심 동인과 불확실성 축", question:"미래를 좌우하는 힘은?",
    macro:"동인 도출 → 영향도·불확실성 평가 → 핵심 축 선정",
    micro:["동인(driving forces) 도출·분류","영향도·불확실성 평가(매트릭스)","상호작용·인과 구조","시나리오 핵심 축 선정"],
    goodPatterns:["불확실성 축 명시","상호작용 분석","근거 평가"],
    badPatterns:["동인 나열","불확실성 무시","축 임의"] },
  { num:"CH.07", title:"미래 예측 결과 (Foresight Results)", color:C.results,
    desc:"시나리오·예측 결과 제시", question:"어떤 미래들이 도출되었나?",
    macro:"시나리오 구성 → 각 미래 서술 → 확률·조건 → 결과 제시",
    micro:["복수 시나리오(2x2 등) 구성","각 미래상의 일관된 서술","발생 조건·전조(early indicators)","Delphi 합의/예측치 제시"],
    goodPatterns:["복수 미래 제시","조건·전조 명시","일관성"],
    badPatterns:["단일 미래","조건 부재","서술 비일관"] },
  { num:"CH.08", title:"논의 / 전략적 함의 (Implications)", color:C.disc,
    desc:"전략·정책 함의", question:"이 미래에 어떻게 대비하나?",
    macro:"시나리오 해석 → 전략·정책 함의 → 강건 전략 → 한계",
    micro:["시나리오별 전략적 함의","정책·의사결정 시사점","불확실성하 강건 전략","예측의 한계·가정 의존성"],
    goodPatterns:["강건 전략 제안","함의 구체화","가정 명시"],
    badPatterns:["함의 부재","단일 처방","한계 회피"] },
  { num:"CH.09", title:"결론 (Conclusion)", color:C.concl,
    desc:"예측 요약·기여·모니터링", question:"이 예측의 기여와 후속은?",
    macro:"질문 재호응 → 핵심 예측 요약 → 기여 → 모니터링·후속",
    micro:["예측 질문에의 응답","핵심 시나리오·예측 요약","방법·실천 기여","지속 모니터링·갱신 제안"],
    goodPatterns:["모니터링 제안","기여 명시","갱신 가능성"],
    badPatterns:["예측 반복","기여 모호","고정된 단정"] },
];

/* ── ㉞ 설계기반 연구 (Design-Based Research / McKenney·Reeves·Bakker) ───── */
export const CHAPTERS_DBR: Chapter[] = [
  { num:"CH.01", title:"서론 (Introduction)", color:C.intro,
    desc:"실천 문제 + 이론 공백의 이중 동기", question:"어떤 실천 문제를 설계로 해결하는가?",
    macro:"실천 현장 문제 → 기존 해법·이론의 한계 → 설계기반 접근 정당화 → 이중 목표(개입+이론)",
    micro:["P1: 교육·실천 현장의 지속 문제","P2: 기존 개입·이론의 한계","P3: 설계기반연구(DBR)가 적합한 이유","P4: 이중 산출 목표(실천적 개입 + 설계 원리)"],
    goodPatterns:["실천+이론 이중 동기","현장 정합성 강조","반복적 설계 예고"],
    badPatterns:["단발 개입","이론 산출 부재","현장 맥락 무시"] },
  { num:"CH.02", title:"이론·개념적 배경 (Theoretical Framework)", color:C.theory,
    desc:"개입을 설계하는 이론적 토대", question:"어떤 이론으로 설계를 안내하는가?",
    macro:"핵심 이론 → 설계를 안내하는 잠정 설계 원리 → 개념 정렬",
    micro:["문제 영역의 핵심 이론","학습·실천 이론과 설계의 연결","잠정적 설계 원리(initial design principles)","개념 틀과 개입 설계 정렬"],
    goodPatterns:["이론→설계원리 연결","잠정 원리 명시","틀 정합"],
    badPatterns:["이론 장식","원리 부재","설계 단절"] },
  { num:"CH.03", title:"선행 연구 (Literature Review)", color:C.lit,
    desc:"유사 개입·설계 선행연구", question:"유사 개입은 무엇을 밝혔나?",
    macro:"유사 개입 연구 → 효과·한계 → 설계 공백 도출",
    micro:["유사 개입·프로그램 선행연구","효과와 실패 요인","맥락 의존성·확장성 논의","본 설계의 공백·기여"],
    goodPatterns:["효과+한계 정리","맥락 강조","공백 도출"],
    badPatterns:["나열식","맥락 무시","공백 막연"] },
  { num:"CH.04", title:"연구방법 (Research Design & Methodology)", color:C.method,
    desc:"반복적 DBR 사이클 설계", question:"어떻게 설계·실행·평가를 반복했나?",
    macro:"DBR 사이클(분석-설계-평가) → 맥락·참여자 → 자료·반복 → 신뢰성",
    micro:["DBR 일반 모델(McKenney & Reeves)과 사이클 구조","연구 맥락·참여자·반복(iteration) 횟수","혼합 자료 수집·분석","타당성·체계성·재현 정보"],
    goodPatterns:["사이클 명시","반복 근거","혼합 자료"],
    badPatterns:["단일 사이클","반복 불명","자료 빈약"] },
  { num:"CH.05", title:"분석·탐색 (Analysis & Exploration)", color:C.midA,
    desc:"문제 분석과 현장 탐색", question:"문제와 맥락을 어떻게 진단했나?",
    macro:"요구 분석 → 현장 맥락 탐색 → 문제 정의 → 설계 요구사항 도출",
    micro:["요구·맥락 분석(needs & context)","이해관계자 탐색·현장 진단","문제의 조작적 정의","설계 요구사항(design requirements) 도출"],
    goodPatterns:["현장 밀착 진단","요구사항 도출","이해관계자 반영"],
    badPatterns:["책상 분석","요구 불명","맥락 생략"] },
  { num:"CH.06", title:"설계·구성 (Design & Construction)", color:C.midB,
    desc:"개입(산출물)의 설계와 제작", question:"개입을 어떻게 설계·구현했나?",
    macro:"설계 원리 적용 → 개입 프로토타입 구성 → 설계 결정 정당화",
    micro:["잠정 설계 원리의 개입 반영","프로토타입·산출물 구성","설계 결정과 근거(design rationale)","반복 간 설계 수정 이력"],
    goodPatterns:["원리→산출 추적성","설계 근거 명시","수정 이력 투명"],
    badPatterns:["근거 없는 설계","원리 무관","수정 은폐"] },
  { num:"CH.07", title:"평가·반성 (Evaluation & Reflection)", color:C.results,
    desc:"DBR의 핵심 — 형성·총괄 평가 + 반성", question:"개입은 효과적이었고 무엇을 배웠나?",
    macro:"형성 평가(사이클별) → 총괄 평가 → 반성 → 설계 원리 정련",
    micro:["사이클별 형성 평가 결과","개입의 총괄 효과·작동 조건","반성(reflection)을 통한 학습","정련된 설계 원리(refined principles) 산출"],
    goodPatterns:["형성+총괄 분리","작동 조건 명시","원리 정련"],
    badPatterns:["평가=만족도만","조건 무시","원리 미산출"] },
  { num:"CH.08", title:"논의 (Discussion)", color:C.disc,
    desc:"설계 원리의 이론적 기여 확립", question:"이 설계가 이론에 무엇을 더하나?",
    macro:"정련 원리 해석 → 이론적 기여 → 전이·확장 가능성 → 한계",
    micro:["정련된 설계 원리의 이론적 위치","실천적·이론적 이중 기여","다른 맥락으로의 전이 가능성","맥락 의존성·일반화 한계"],
    goodPatterns:["이중 기여 명시","전이 조건 논의","한계 정직"],
    badPatterns:["실천만 강조","이론 기여 부재","과잉 일반화"] },
  { num:"CH.09", title:"결론 (Conclusion)", color:C.concl,
    desc:"개입+설계원리의 통합 결론", question:"무엇을 만들었고 무엇을 알게 됐나?",
    macro:"문제 재호응 → 개입·설계원리 요약 → 기여 → 후속 사이클",
    micro:["문제의 설계적 해결 선언","개입 산출물·설계 원리 요약","실천·이론 기여","후속 설계 사이클·확장"],
    goodPatterns:["이중 산출 요약","기여 구체화","후속 사이클 제안"],
    badPatterns:["개입만 요약","원리 누락","논의 반복"] },
];

export const EXT_CHAPTERS: Record<string, Chapter[]> = {
  phen: CHAPTERS_PHEN, herm: CHAPTERS_HERM, phil: CHAPTERS_PHIL, sim: CHAPTERS_SIM,
  na: CHAPTERS_NA, ds: CHAPTERS_DS, dh: CHAPTERS_DH, conv: CHAPTERS_CONV, fut: CHAPTERS_FUT,
  dbr: CHAPTERS_DBR,
};
