"use client";

/* ════════════════════════════════════════════════════════════
   v24: 통합 아웃라인 아이콘 시스템
   - 모든 UI 아이콘을 lucide-react 기반 Outline Icon으로 통일
   - 선(line)만으로 구성 / 단색(currentColor) / Rounded Stroke / Minimal
   - 기존 이모지(🔬 📚 ✍ …) → 의미 키 또는 이모지 키로 매핑
═══════════════════════════════════════════════════════════════ */

import {
  Microscope, FlaskConical, BookOpen, BookText, PenLine, SquarePen, Pencil,
  Search, Send, ClipboardList, Hexagon, MessageSquare, MessagesSquare,
  GraduationCap, School, Library, FileText, Files, FileSpreadsheet,
  Home, Settings, Bot, Crown, Target, BarChart3, Sparkles, CheckCircle2,
  Check, AlertTriangle, XCircle, X, FolderOpen, Folder, Lightbulb, Ruler,
  Save, Globe, Calendar, CalendarDays, Leaf, Hourglass, Hand, NotebookPen,
  Menu, Paperclip, Scale, Palette, Unlock, Lock, Download, Upload, Trash2, AlignLeft, AlignCenter, AlignRight,
  Key, Star, ChevronDown, ChevronUp, ChevronRight, ChevronLeft, Brain, Plus, Minus,
  Link2, Database, Archive, RefreshCw, Timer, Laptop, Cloud, Mail, Circle,
  CircleDot, HelpCircle, Map, Bell, CreditCard, Rocket, Shield, ShieldCheck,
  Diamond, ArrowRight, ArrowLeft, ArrowLeftRight, Inbox, Languages, Quote,
  Square, Flag, MapPin,
  Network, Share2, SpellCheck, ScanLine, Copy, ListChecks, GitCompare,
  Boxes,
  type LucideIcon,
} from "lucide-react";

/** 의미 기반 키 (메뉴/데이터에서 사용) */
const SEMANTIC: Record<string, LucideIcon> = {
  // 연구 흐름
  research: Microscope,
  literature: BookOpen,
  writing: PenLine,
  review: Search,
  validation: Search,
  submission: Send,
  // AI 엔진
  workflow: ClipboardList,
  structure: Hexagon,
  chat: MessageSquare,
  analyzer: FlaskConical,
  advisor: GraduationCap,
  mentoring: GraduationCap,
  library: Library,
  litReview: BookText,
  critique: SquarePen,
  // 공통/시스템
  dashboard: Home,
  home: Home,
  admin: Crown,
  settings: Settings,
  engine: Bot,
  citation: Quote,
  logo: Sparkles,
  // 상태/액션
  check: CheckCircle2,
  ok: CheckCircle2,
  warn: AlertTriangle,
  warning: AlertTriangle,
  error: XCircle,
  close: X,
  menu: Menu,
  save: Save,
  download: Download,
  upload: Upload,
  trash: Trash2,
  alignLeft: AlignLeft,
  alignCenter: AlignCenter,
  alignRight: AlignRight,
  refresh: RefreshCw,
  search: Search,
  link: Link2,
  globe: Globe,
  language: Languages,
  calendar: CalendarDays,
  timer: Timer,
  idea: Lightbulb,
  target: Target,
  ruler: Ruler,
  chart: BarChart3,
  brain: Brain,
  database: Database,
  folder: Folder,
  folderOpen: FolderOpen,
  edit: Pencil,
  plus: Plus,
  minus: Minus,
  file: FileText,
  files: Files,
  shield: Shield,
  shieldCheck: ShieldCheck,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  bell: Bell,
  mail: Mail,
  card: CreditCard,
  rocket: Rocket,
  palette: Palette,
  scale: Scale,
  paperclip: Paperclip,
  star: Star,
  leaf: Leaf,
  laptop: Laptop,
  cloud: Cloud,
  map: Map,
  inbox: Inbox,
  hand: Hand,
  note: NotebookPen,
  pencil: Pencil,
  help: HelpCircle,
  circle: Circle,
  dot: CircleDot,
  diamond: Diamond,
  hourglass: Hourglass,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  school: School,
  flag: Flag,
  pin: MapPin,
  spreadsheet: FileSpreadsheet,
  // v41 신규
  network: Network,
  share: Share2,
  spell: SpellCheck,
  aiscan: ScanLine,
  plagiarism: Copy,
  checklist: ListChecks,
  compare: GitCompare,
  method: Boxes,
  schedule: CalendarDays,
};

/** 이모지 → 아웃라인 아이콘 (인라인 교체 편의) */
const EMOJI: Record<string, LucideIcon> = {
  "🤖": Bot,
  "🔬": Microscope,
  "📋": ClipboardList,
  "📚": BookOpen,
  "💡": Lightbulb,
  "✅": CheckCircle2,
  "⚠": AlertTriangle,
  "⚠️": AlertTriangle,
  "📝": SquarePen,
  "🛡": Shield,
  "🛡️": Shield,
  "📊": BarChart3,
  "✕": X,
  "✗": X,
  "✍": PenLine,
  "✍️": PenLine,
  "📂": FolderOpen,
  "⬡": Hexagon,
  "💾": Save,
  "📄": FileText,
  "◈": Diamond,
  "🧑‍🏫": GraduationCap,
  "🏫": School,
  "📁": Folder,
  "✓": Check,
  "🌐": Globe,
  "📅": CalendarDays,
  "📆": CalendarDays,
  "🗓": CalendarDays,
  "🗓️": CalendarDays,
  "🔍": Search,
  "✦": Sparkles,
  "⚙": Settings,
  "⚙️": Settings,
  "📐": Ruler,
  "🌿": Leaf,
  "⏳": Hourglass,
  "⏱": Timer,
  "⏱️": Timer,
  "📖": BookText,
  "💬": MessageSquare,
  "❌": XCircle,
  "👋": Hand,
  "✏": Pencil,
  "✏️": Pencil,
  "🗒": NotebookPen,
  "🗒️": NotebookPen,
  "👑": Crown,
  "☰": Menu,
  "📎": Paperclip,
  "⚖": Scale,
  "⚖️": Scale,
  "🎨": Palette,
  "🔓": Unlock,
  "🔒": Lock,
  "🔐": Lock,
  "📥": Download,
  "🗑": Trash2,
  "🗑️": Trash2,
  "📤": Upload,
  "🔑": Key,
  "★": Star,
  "🎯": Target,
  "🧠": Brain,
  "📑": Files,
  "🔗": Link2,
  "🗄": Database,
  "🗄️": Database,
  "🏠": Home,
  "🔄": RefreshCw,
  "↺": RefreshCw,
  "💻": Laptop,
  "☁": Cloud,
  "☁️": Cloud,
  "📨": Mail,
  "✉": Mail,
  "✉️": Mail,
  "❓": HelpCircle,
  "🗺": Map,
  "🗺️": Map,
  "🔔": Bell,
  "💳": CreditCard,
  "🎓": GraduationCap,
  "🚀": Rocket,
  "📈": BarChart3,
  "📉": BarChart3,
  "💼": ClipboardList,
  "→": ArrowRight,
  "←": ArrowLeft,
  "↔": ArrowLeftRight,
  "●": Circle,
  "○": Circle,
  "🔴": CircleDot,
  "🟡": CircleDot,
  "🟢": CircleDot,
  "🔵": CircleDot,
  "🟣": CircleDot,
  "⚪": Circle,
  "⚫": CircleDot,
  "🟩": Square,
  "🟦": Square,
  "🟥": Square,
  "🟨": Square,
  "🟪": Square,
  "⬜": Square,
  "⬛": Square,
  "▼": ChevronDown,
  "▾": ChevronDown,
  "▲": ChevronUp,
  "▴": ChevronUp,
  "▸": ChevronRight,
  "▶": ChevronRight,
  "◀": ChevronLeft,
};

export interface IconProps {
  /** 의미 키(예: "research") 또는 이모지(예: "🔬") */
  name: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
}

export function Icon({ name, className, size, strokeWidth = 1.75 }: IconProps) {
  const Cmp = SEMANTIC[name] ?? EMOJI[name] ?? HelpCircle;
  return (
    <Cmp
      className={className}
      size={size}
      strokeWidth={strokeWidth}
      aria-hidden
    />
  );
}

export default Icon;
